Adds Allwinner D1 support to mainline u-boot
AOSC-Archive/u-boot pull request #1
Opened 2022-09-26 13:02 UTC by Jamm02

With the exception of the spi driver, the series of changes adds Allwinner D1 functionality to the mainline u-boot.

2022-09-29 07:59 UTC, Icenowy commented
Your patches still miss Signed-off-by by the original authors.

2022-09-29 08:00 UTC, Icenowy commented
and commit message should be consistent, among your own commits, and with existing commits.

2022-09-30 04:10 UTC, Icenowy commented
Your signed-off-by should coexist with the original one, and come latter.

2022-10-04 03:07 UTC, Jamm02 commented
@Icenowy, I have updated the commit messages according to previous suggestions.

2022-10-06 18:34 UTC, Jamm02 commented
@liushuyu @Icenowy is there anything else I should add to the commits/code?

2022-10-06 20:44 UTC, liushuyu commented
> @liushuyu @Icenowy is there anything else I should add to the commits/code?

I am not quite sure why you pinged me as I am not a mentor of your project, not even an off-mentor.

But anyways, I will do a very basic pass of review purely on the code organization and basic code hygiene.

2022-10-06 20:57 UTC, liushuyu commented on arch/riscv/cpu/thead/cache.c
> +#endif
Why is this commented out? If the code is unused and you are done with the implementation, you should remove it.

2022-10-06 20:57 UTC, liushuyu commented on drivers/clk/sunxi/clk_d1.c
> +// }
Ditto with the code comments. Please either fix the function or remove it entirely.

2022-10-06 20:57 UTC, liushuyu commented on drivers/clk/sunxi/clk_ncatv2.h
> + * Copyright (C) 2021 Moteen Shah <moteenshah.02@gmail.com>
```suggestion
 * Copyright (C) 2022 Moteen Shah <moteenshah.02@gmail.com>
```

Also, did you author this file entirely, or is it based on Samuel Holland's implementation?

2022-10-06 20:57 UTC, liushuyu commented on arch/riscv/cpu/thead/cache.c
> +
Copyright statements?

2022-10-06 20:57 UTC, liushuyu commented on include/dt-bindings/mailbox/sun20i-d1-msgbox.h
> +
Ditto with copyright statements.

2022-10-06 20:57 UTC, liushuyu commented on drivers/usb/musb-new/sunxi.c
> +	#ifndef CONFIG_TARGET_SUNXI
Inconsistent indentation.

2022-10-08 10:45 UTC, Jamm02 commented on drivers/clk/sunxi/clk_ncatv2.h
> + * Copyright (C) 2021 Moteen Shah <moteenshah.02@gmail.com>
Samuel added the clock header file for sun50i_h6 because D1 utilises the same macros; however, if the additions are to be made generic, the macros must be defined in a distinct header file unique to D1; therefore, should I put Samuel or the original creator of the sun50i_h6 header in the copyright?

2022-10-10 04:51 UTC, liushuyu commented on drivers/clk/sunxi/clk_ncatv2.h
> + * Copyright (C) 2021 Moteen Shah <moteenshah.02@gmail.com>
> Samuel added the clock header file for sun50i_h6 because D1 utilises the same macros; however, if the additions are to be made generic, the macros must be defined in a distinct header file unique to D1; therefore, should I put Samuel or the original creator of the sun50i_h6 header in the copyright?

I think you need to include the copyright of everyone involved (as far as you understand it).

2022-10-12 02:47 UTC, Icenowy requested changes

2022-10-12 02:47 UTC, Icenowy commented on arch/riscv/Kconfig
> +config TARGET_SUNXI
Should we try to get some consistency between arch/arm sunxi and arch/riscv one?

2022-10-12 02:47 UTC, Icenowy commented on Kconfig
> +source "board/sunxi/Kconfig"
This is quite dirty and should not happen.

2022-10-12 02:47 UTC, Icenowy commented on drivers/pinctrl/sunxi/Kconfig
> +if ARCH_SUNXI || TARGET_SUNXI
Consider use ARCH_SUNXI for both ARM and RISCV?

2022-10-12 02:47 UTC, Icenowy commented on arch/riscv/lib/cache.c
> +__weak void invalidate_icache_range(unsigned long start, unsigned long end)
Should this be in a splitted commit?

2022-10-12 02:47 UTC, Icenowy commented on board/sunxi/Kconfig
> +if TARGET_SUNXI
Should we just move these things from arch/arm/mach-sunxi/Kconfig instead of guard it here with RISCV-specific option?

2022-10-19 08:34 UTC, Jamm02 commented on drivers/pinctrl/sunxi/Kconfig
> +if ARCH_SUNXI || TARGET_SUNXI
Apologies for the late reply I was occupied with my college mid-semester exams, since we are not using the arch headers there has to be a way to distinguish D1 from others that are using arch-specific headers, I found TARGET_SUNXI to be a way but for the seamless merger, it will require the arch headers.

2022-10-19 08:35 UTC, Jamm02 commented on board/sunxi/Kconfig
> +if TARGET_SUNXI
Yes I'll do the needful

2022-10-19 11:51 UTC, Jamm02 commented on drivers/pinctrl/sunxi/Kconfig
> +if ARCH_SUNXI || TARGET_SUNXI
also should I make a riscv/sunxi same as arm/mach-sunxi

2022-10-22 14:49 UTC, Jamm02 commented on board/sunxi/Kconfig
> +if TARGET_SUNXI
marking this as resolved, added a new Kconfig specific to D1, which can be merged into the current Kconfig once all the arch-specific headers are dropped until then there has to be a different file or a guard to distinguish the D1(Note we are not using arch-specific headers for the D1)

2022-10-22 14:51 UTC, Jamm02 commented on arch/riscv/Kconfig
> +config TARGET_SUNXI
There has to be a distinguishing factor between D1 and other boards since we are not using arch-specific headers for the D1, once all the arch-specific headers are dropped for sunxi boards it can be consistent with arch-sunxi following the semantics after headers are dropped.

2022-10-22 14:52 UTC, Jamm02 commented on drivers/pinctrl/sunxi/Kconfig
> +if ARCH_SUNXI || TARGET_SUNXI
marking this as resolved for now owing to the previous conversations in the above threads.

2022-10-22 18:51 UTC, Jamm02 commented on arch/riscv/lib/cache.c
> +__weak void invalidate_icache_range(unsigned long start, unsigned long end)
The change(adding __weak for other functions with the same name to override the definition) essentially affects the same feature,  I can still split it if advised.

2022-10-24 11:11 UTC, Jamm02 commented on Kconfig
> +source "board/sunxi/Kconfig"
made the required changes.

2022-10-25 05:37 UTC, Icenowy commented on arch/riscv/lib/cache.c
> +__weak void invalidate_icache_range(unsigned long start, unsigned long end)
I think you'd split it.

2022-10-25 05:41 UTC, Icenowy requested changes

2022-10-25 05:41 UTC, Icenowy commented on Kconfig
> +				RISCV || ARCH_ZYNQMP)
I think this breaks arm sunxi.

2022-10-25 05:41 UTC, Icenowy commented on board/sunxi/Kconfig.sun20i
> +if TARGET_SUNXI
Sorry but I still want you to split this.

2022-10-25 05:41 UTC, Icenowy commented on common/spl/Kconfig
> +	depends on RISCV && SPL_RISCV_MMODE && RISCV_SMODE && SPL_LOAD_FIT
Why bother add SPL changes if you do not support SPL now?

2022-10-25 05:41 UTC, Icenowy requested changes

2022-10-25 05:41 UTC, Icenowy commented on configs/nezha_defconfig
> +CONFIG_SYS_MEMTEST_END=0x60000000
Why memtest?

2022-10-26 17:06 UTC, Jamm02 commented on common/spl/Kconfig
> +	depends on RISCV && SPL_RISCV_MMODE && RISCV_SMODE && SPL_LOAD_FIT
have removed it

2022-10-26 17:07 UTC, Jamm02 commented on board/sunxi/Kconfig.sun20i
> +if TARGET_SUNXI
I have split it into 3 commits, have a look.

2022-10-26 17:08 UTC, Jamm02 commented on Kconfig
> +				RISCV || ARCH_ZYNQMP)
well arch sunxi uses binman internally so there wont be a case of !binman && arch_sunxi, anyways removed it.

2022-10-26 17:09 UTC, Jamm02 commented on arch/riscv/lib/cache.c
> +__weak void invalidate_icache_range(unsigned long start, unsigned long end)
done the required changes

2022-10-26 17:11 UTC, Jamm02 commented on configs/nezha_defconfig
> +CONFIG_SYS_MEMTEST_END=0x60000000
That was added during the testing and development phase of Allwinner D1 and can be removed, but if someone wants to run their own tests it is functional.

2022-10-27 02:15 UTC, Icenowy requested changes

2022-10-27 02:15 UTC, Icenowy commented on arch/riscv/lib/cache.c
> +__weak void invalidate_icache_range(unsigned long start, unsigned long end)
Your sequence of two commits are reversed, thus your first commit won't pass build.

2022-10-27 02:16 UTC, Icenowy requested changes
Your sequence of commits is a mess here too.

2022-10-27 02:23 UTC, Icenowy commented
Please keep the bisectibility of all these codes. (that means, if I checkout any intermediate commits of this PR, it should still pass build)

2022-10-27 02:23 UTC, Icenowy requested changes

2022-10-27 02:23 UTC, Icenowy commented on board/sunxi/Kconfig.sun20i
> +if TARGET_SUNXI
Sorry but this is not I wanted, I want you to split this from arch/arm/mach-sunxi/Kconfig, not split here.

2022-10-28 09:42 UTC, Icenowy commented
Many commit messages need rework to be more detailed and explain technical details of the commits.

2022-10-28 09:42 UTC, Icenowy requested changes

2022-10-28 09:42 UTC, Icenowy commented on board/sunxi/Kconfig.sun20i
> +	select SUPPORT_SPL
Are you sure you implemented SPL?

2022-10-28 09:42 UTC, Icenowy commented on arch/riscv/lib/cache.c
> +__weak void invalidate_icache_range(unsigned long start, unsigned long end)
Your sequence is okay now, but the commit message is total mess. Please rework it to be more generic, and represent what __weak does.

2022-10-28 12:59 UTC, Jamm02 commented on board/sunxi/Kconfig.sun20i
> +if TARGET_SUNXI
changed it to use current Kconfig.

2022-10-29 11:42 UTC, Jamm02 commented on arch/riscv/lib/cache.c
> +__weak void invalidate_icache_range(unsigned long start, unsigned long end)
done with the changes.

2022-10-30 04:31 UTC, Icenowy requested changes

2022-10-30 04:31 UTC, Icenowy commented on arch/riscv/Kconfig
> +	select SUPPORT_SPL
Still, SUPPORT_SPL?! Are you sure?

2022-10-30 04:31 UTC, Icenowy commented on include/configs/sunxi-common.h
> +/* I2C */
Still a mess, I doubt this commit should be at least 3, or maybe 5, or maybe more commits.

2022-10-30 04:31 UTC, Icenowy commented on arch/riscv/dts/sun20i-d1-nezha.dts
> +		compatible = "xradio,xr829-bt";
Device w/o legal DT binding.

2022-10-30 04:34 UTC, Icenowy commented
Finally you get able to write some code that I expect you to write in Day 1, however this snippet of code only values a few person hour, and tomorrow is the deadline, so I doubt whether you can finish it on time.

I suggest you to close this PR and give up.

2022-10-30 06:22 UTC, Jamm02 commented
> Finally you get able to write some code that I expect you to write in Day 1, however this snippet of code only values a few person hour, and tomorrow is the deadline, so I doubt whether you can finish it on time.
> 
> I suggest you to close this PR and give up.

Any additional suggestions will be really appreciated, as you believe the code is logically sound; any other suggestions can be incorporated within a day.
I have worked hard on the project for the past four months, and closing the PR is not an option for me. I am willing to work beyond the project's official timeline until you believe the PR is mergeable. I have tested all of the commits individually, and none of them breaks any other boards. Regards for your valuable time.

2022-10-30 06:55 UTC, liushuyu commented
> I am willing to work beyond the project's official timeline until you believe the PR is mergeable.

As a mentor of a different project in this organization, I need to clarify that it is against OSPP's rules to request extensions this late in the timeline. In this case, you might not receive any stipend/compensation for your work.

You must have the resolve to finish this project, turning things around within several days, or prepare for a disappointing result. OSPP this year will only count PR successfully merged before the deadline toward your project contribution.

This year's deadline is October 31, 2022, at 23:59:59 (UTC+8:00) [for your convenience, it should be 21:29:59 Monday, October 31, 2022, in Indian Time (UTC+5:30)].

2022-10-30 08:31 UTC, Jamm02 commented
> As a mentor of a different project in this organization, I need to clarify that it is against OSPP's rules to request extensions this late in the timeline. In this case, you might not receive any stipend/compensation for your work.

The reason I took on this project was not for the stipend but for the experience; my focus is to complete the project and have it merged; the compensation is secondary.

2022-10-30 10:46 UTC, Jamm02 commented on arch/riscv/Kconfig
> +	select SUPPORT_SPL
yes it has been implemented

2022-10-30 18:16 UTC, Jamm02 commented on arch/riscv/dts/sun20i-d1-nezha.dts
> +		compatible = "xradio,xr829-bt";
added the legalities

2022-10-30 18:17 UTC, Jamm02 commented on include/configs/sunxi-common.h
> +/* I2C */
splitted

2022-10-31 07:03 UTC, Icenowy commented
Sorry but I now think you didn't get what a SPL is.

2022-10-31 07:37 UTC, Jamm02 commented
> Sorry but I now think you didn't get what a SPL is.

Without the SPL changes introduced, it won't be able to parse the input tree.

2022-10-31 07:52 UTC, Icenowy commented
在 2022-10-31星期一的 00:37 -0700，Moteen Shah写道：
> > Sorry but I now think you didn't get what a SPL is.
> 
> Without the SPL changes introduced, it won't be able to parse the
> input tree.

Then where your SPL? Is it usable?

If not, why do you set SUPPORT_SPL?

>

2022-10-31 09:25 UTC, Jamm02 commented
> > Sorry but I now think you didn't get what a SPL is. Without the SPL changes introduced, it won't be able to parse the input tree.
> Then where is your SPL? Is it usable? If not, why do you set SUPPORT_SPL?

it builds the SPL image already configured in board/sunxi/Kconfig, [this](https://github.com/u-boot/u-boot/commit/a51715d07a78890a9f0331daebf373c2100a9abd) commit allows it to use the images

2022-10-31 16:59 UTC, Icenowy commented
Sorry but finally this does not contain as much useful production as needed. Closing.

2022-10-31 16:59 UTC, closed without merging

2022-10-31 18:10 UTC, Jamm02 commented
> Sorry but finally this does not contain as much useful production as needed. Closing.

Please provide a clear explanation of why it is not being merged because the goal of the project as mentioned on the OSPP site is being accomplished, I have demonstrated that the series of changes add support to Allwinner D1 and do not break any other board.

2022-10-31 21:06 UTC, liushuyu commented
> Please provide a clear explanation of why it is not being merged

Although I am not your mentor, I have monitored this project for a while. Let me give you my preliminary thoughts on this.

> because the goal of the project as mentioned on the OSPP site is being accomplished

First of all, the requirements clearly stated that "Basic bootloader functions, can boot a Linux kernel, and **upstreaming all relevant code changes**" however the last part was clearly not done. Your mentor gated your patches because they will need to vouch for your changes when you submit them to the U-boot upstream. When your code quality is subpar, they can't let the unfinished code slip upstream.

> I have demonstrated that the series of changes add support to Allwinner D1 and do not break any other board

I have discussed with your mentor the project status and progression. It seems to me that there are some issues with communication and mutual understanding. You seem to have trouble understanding some basic concepts you thought you had well understood, like how SPL (Secondary Program Loader) works.

It is unfortunate that it has to end like this. To reflect on this, we also have our own issues, where we should identify the communication problems early and help you manage the time and project progression better.

Speaking of which, may I ask you why you chose this project despite its advanced difficulty (given that you might have become aware that a more challenging project is more likely to fail)?

2022-11-02 17:23 UTC, Jamm02 commented
> > Please provide a clear explanation of why it is not being merged
> 
> Although I am not your mentor, I have monitored this project for a while. Let me give you my preliminary thoughts on this.
> 
> > because the goal of the project as mentioned on the OSPP site is being accomplished
> 
> First of all, the requirements clearly stated that "Basic bootloader functions, can boot a Linux kernel, and **upstreaming all relevant code changes**" however the last part was clearly not done. Your mentor gated your patches because they will need to vouch for your changes when you submit them to the U-boot upstream. When your code quality is subpar, they can't let the unfinished code slip upstream.
> 
> > I have demonstrated that the series of changes add support to Allwinner D1 and do not break any other board
> 
> I have discussed with your mentor the project status and progression. It seems to me that there are some issues with communication and mutual understanding. You seem to have trouble understanding some basic concepts you thought you had well understood, like how SPL (Secondary Program Loader) works.
> 
> It is unfortunate that it has to end like this. To reflect on this, we also have our own issues, where we should identify the communication problems early and help you manage the time and project progression better.
> 
> Speaking of which, may I ask you why you chose this project despite its advanced difficulty (given that you might have become aware that a more challenging project is more likely to fail)?

Thanks for the detailed review, the reason I took on the project was for interest in computer architecture in general and my previous experience in building embedded projects, so I started with this project as it complimented my skills thereby I was able to complete the "boot the Linux kernel" part of the project, but I wasn't a seasoned open source contributor (second year undergrad degree when I joined the project) so I expected some guidance from the mentors as I have seen my peers in GSOC and OSPP having weekly meets with their respective mentors regarding the project but I was wrong on my expectations. I had my previous contributions merged in red hat organizations before applying for the project under OSPP. On the topic of subpar quality of code. I updated my mentor with regular commits so she could have an overall view of the final product. I still feel the project would have been mergeable if proper communication from the start was established.
Nevertheless thank you for your time and effort.